## Numpy 연습문제

In [1]:
import numpy as np

## 1. 길이가 10인 0-벡터를 만드세요.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [3]:
np.where(np.arange(10)==4, 1, 0), np.eye(1, 10, k=4)

(array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]))

## 3. 10부터 49까지의 값을 가지는 벡터를 만드세요.

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4. 위(3번) 벡터의 순서를 바꾸세요.

In [12]:
np.arange(49, 9, -1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [6]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [7]:
a = np.array([1,2,0,0,4,0], int)
a[a != 0]

array([1, 2, 4])

## 7. 3x3 단위 행렬(identity matrix)을 만드세요.

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8. 난수 원소를 가지는 3x3 행렬을 만드세요.

In [9]:
a = np.random.random(9).reshape(3, 3)

## 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.(값)

In [10]:
a[np.argmax(a)//3, np.argmax(a)%3], np.argmin(a)

(0.9787782064445956, 2)

## 10. 위(8번)에서 만난 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [11]:
np.mean(a, axis = 1), np.mean(a, axis = 0)

(array([0.43658901, 0.47343122, 0.58307248]),
 array([0.22572713, 0.70954781, 0.55781777]))